### ISSUE TITLE
Regression on 1.20240826.1 

### ISSUE THREAD

**Issue by marvin4ward** [web2py/py4web#916]
After upgrade from 1.20240713.1 to 1.20240826.1 it is not possible anymore start `py4web` as a binary.
```
(test) root@793fc7864018:~# py4web version
py4web: 1.20240713.1
(test) root@793fc7864018:~# pip install py4web==1.20240826.1
Collecting py4web==1.20240826.1
  Using cached py4web-1.20240826.1-py3-none-any.whl.metadata (8.6 kB)
....SKIP....
  Attempting uninstall: py4web
    Found existing installation: py4web 1.20240713.1
    Uninstalling py4web-1.20240713.1:
      Successfully uninstalled py4web-1.20240713.1
Successfully installed ombott-2.2 py4web-1.20240826.1
(test) root@793fc7864018:~# py4web version
Traceback (most recent call last):
  File "/root/test/bin/py4web", line 5, in <module>
    from py4web.core import cli
  File "/root/test/lib/python3.12/site-packages/py4web/__init__.py", line 20, in <module>
    from .core import HTTP  # checks for version compatibility; bottle
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/test/lib/python3.12/site-packages/py4web/core.py", line 63, in <module>
    from . import server_adapters
ImportError: cannot import name 'server_adapters' from partially initialized module 'py4web' (most likely due to a circular import) (/root/test/lib/python3.12/site-packages/py4web/__init__.py)
```

**Comment by marvin4ward** [comment]
Confirm issue resolution.

**Comment by marvin4ward** [comment]
https://github.com/web2py/py4web/commit/c2bf12484ef6194cf1701b6cc2ee4b5116f24290
